export const background = '#e8ecef';
export const timeSale = '#ff5a5a';
export const dCheck = '#ff5a29';
export const white = '#ffffff';
export const disable = '#d9d9d9';
export const divider = '#e8ecef';
export const main = '#32a86f';
export const sub = '#70ab4f';
export const textButton = '#ffffff';
export const text = '#3d3d3d';
export const black = '#464646';
export const itemHeader = '#F2F6F4';
export const textGray = '#717171';
export const gray = '#979797';
export const update = '#d5d5d5';
export const lightGray = '#F4F5F4';
export const yellowGray = '#F9FAF9';
export const translate = 'rgba(0, 0, 0, 0)';
export const header = '#e6e6e6';

// 22pt = 14
