# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MAEMI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MAEMI

  target 'MAEMI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'CodePush', :path => '../node_modules/react-native-code-push'

  end

  target 'MAEMITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
